version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      crates:
        patterns:
          - "*"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/xtask" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      crates:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"